#!/usr/bin/env bash
# TASK1 Step B — unified drop_pct=45 across 3 backbones (ref_e=5).
# Generated by task1_step_b_unified.py
set -uo pipefail

ROOT=/mnt/workspace/juyoung_ha/rho_pretrain
SWEEP=$ROOT/logs/auto_overnight
SUMMARY_K1=$SWEEP/keti1/summary.jsonl
SUMMARY_K2=$SWEEP/keti2/summary.jsonl
mkdir -p "$SWEEP/keti1" "$SWEEP/keti2"
touch "$SUMMARY_K1" "$SUMMARY_K2"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gracm
cd "$ROOT"

EVAL_SEEDS=(42 43 44)
EVAL_DATASETS=ETTh1,ETTh2,ETTm1,ETTm2,weather,exchange
EVAL_HORIZONS=96,192,336,720
DROP=45

# Backbone-specific best hparams — bs >= 32, ref_e = 5, full UTSD, 1 epoch
# Timer:  bs=64 lr=3e-4 (best from earlier sweeps)
# Moirai: bs=32 lr=1e-4 (best, packed-attn safe)
# MOMENT: bs=64 lr=1e-4 (best closest)

run_pair_unified () {
  # backbone name batch lr script rho_mode eval_mode base_flag rho_flag eval_extra baseline_src host_summary
  local backbone=$1 name=$2 batch=$3 lr=$4 baseline_src=$5 host=$6
  local script rho_mode eval_mode base_flag rho_flag eval_json eval_extra
  case $backbone in
    timer)  script=scripts/pretrain_timer.py;  rho_mode=rho_cm;       eval_mode=eval_zero_shot_sweep; base_flag=--baseline-ckpt; rho_flag=--rho-cm-ckpt;       eval_json=zero_shot_results.json; eval_extra="";;
    moirai) script=scripts/pretrain_moirai.py; rho_mode=rho_cm;       eval_mode=eval_zero_shot_sweep; base_flag=--baseline-ckpt; rho_flag=--rho-cm-ckpt;       eval_json=zero_shot_results.json; eval_extra="";;
    moment) script=scripts/pretrain_moment.py; rho_mode=patch_rho_cm; eval_mode=eval_sweep;            base_flag=--baseline-ckpt; rho_flag=--patch-rho-cm-ckpt; eval_json=linear_probe_results.json; eval_extra="--probe-epochs 5";;
  esac

  local out=$SWEEP/$host/${backbone}__${name}
  mkdir -p "$out"
  local marker=$out/DONE
  if [[ -f $marker ]]; then echo "[skip] $backbone/$name (DONE)"; return 0; fi

  echo "============================================"
  echo "[$(date '+%H:%M:%S')] $backbone/$name START (drop=$DROP, ref_e=5)"
  echo "============================================"

  if [[ ! -f $out/baseline/best.pt ]]; then
    if [[ -n "$baseline_src" && -f "$baseline_src/best.pt" ]]; then
      echo "[reuse] baseline ← $baseline_src"
      mkdir -p "$out/baseline"
      ln -sf "$baseline_src/best.pt" "$out/baseline/best.pt"
      [[ -f "$baseline_src/metrics.json" ]] && ln -sf "$baseline_src/metrics.json" "$out/baseline/metrics.json"
    else
      echo "[$(date '+%H:%M:%S')] baseline pretrain (no source)"
      mkdir -p "$out/baseline"
      python "$script" --mode baseline --epochs 1 --batch-size "$batch" --lr "$lr" \
        --seed 42 --out-dir "$out/baseline" > "$out/baseline/pretrain.log" 2>&1
      [[ ! -f $out/baseline/best.pt ]] && { tail -20 "$out/baseline/pretrain.log"; return 1; }
    fi
  fi

  if [[ ! -f $out/rho/best.pt ]]; then
    echo "[$(date '+%H:%M:%S')] rho pretrain"
    mkdir -p "$out/rho"
    python "$script" --mode "$rho_mode" --epochs 1 --batch-size "$batch" --lr "$lr" \
      --seed 42 --drop-pct "$DROP" --ref-epochs 5 \
      --out-dir "$out/rho" > "$out/rho/pretrain.log" 2>&1
    [[ ! -f $out/rho/best.pt ]] && { tail -30 "$out/rho/pretrain.log"; return 1; }
  fi

  for seed in "${EVAL_SEEDS[@]}"; do
    local eval_out=$out/eval_seed${seed}
    [[ -f $eval_out/$eval_json ]] && { echo "[skip] eval seed=$seed exists"; continue; }
    mkdir -p "$eval_out"
    echo "[$(date '+%H:%M:%S')] eval seed=$seed"
    python "$script" --mode "$eval_mode" --seed "$seed" \
      --eval-datasets "$EVAL_DATASETS" --eval-horizons "$EVAL_HORIZONS" \
      --out-dir "$eval_out" $eval_extra \
      $base_flag "$out/baseline/best.pt" $rho_flag "$out/rho/best.pt" \
      > "$eval_out/eval.log" 2>&1
    [[ ! -f $eval_out/$eval_json ]] && { tail -20 "$eval_out/eval.log"; return 1; }
  done

  touch "$marker"
  local now=$(date '+%Y-%m-%dT%H:%M:%S')
  local summary_file
  [[ $host == keti_1 ]] && summary_file=$SUMMARY_K1 || summary_file=$SUMMARY_K2
  echo "{\"time\":\"$now\",\"host\":\"$host\",\"backbone\":\"$backbone\",\"name\":\"$name\",\"batch\":$batch,\"lr\":$lr,\"epochs\":1,\"drop_pct\":$DROP,\"ref_epochs\":5,\"task\":\"task1_unified\",\"status\":\"ok\"}" >> "$summary_file"
  echo "[$(date '+%H:%M:%S')] $backbone/$name DONE"
}

# Run order: Timer (likely already done from ablation), then MOMENT/Moirai.
# Same machine should get backbones based on existing baselines.

# This script is run on EACH host separately — see launcher for host-specific calls.
HOST=$1   # keti_1 or keti_2

if [[ $HOST == keti_1 ]]; then
  # Moirai (keti_1) — uses Moirai mixture_forecast ref (script default)
  run_pair_unified moirai "bs32_lr1e-4_e1_d${DROP}_re5_unif" 32 1e-4 \
    "$SWEEP/keti1/moirai__bs32_lr1e-4_e1_d20/baseline" "keti_1"
elif [[ $HOST == keti_2 ]]; then
  # Timer + MOMENT (keti_2)
  # Timer config might already exist from ablation:
  TIMER_FROM_ABLATION=$SWEEP/keti2/timer__bs64_lr3e-4_e1_d${DROP}_re5
  if [[ -f $TIMER_FROM_ABLATION/DONE ]]; then
    echo "[skip] timer config already done from ablation: $TIMER_FROM_ABLATION"
  else
    run_pair_unified timer "bs64_lr3e-4_e1_d${DROP}_re5_unif" 64 3e-4 \
      "$SWEEP/keti2/timer__bs64_lr3e-4_e1_d20/baseline" "keti_2"
  fi
  # MOMENT — uses realtime masked-recon ref (script default)
  run_pair_unified moment "bs64_lr1e-4_e1_d${DROP}_re5_unif" 64 1e-4 \
    "$SWEEP/keti2/moment__bs64_lr1e-4_e1_d10/baseline" "keti_2"
fi

echo "[$(date '+%H:%M:%S')] task1 unified ($HOST) ALL DONE"
