"""TASK1 Step B — pick best drop_pct from Timer ablation, apply to all 3.

After Timer drop ablation finishes, this script:
1. Reads all timer__bs64_lr3e-4_e1_d{N}_re5/eval_seed{42,43,44} results
2. Picks the drop_pct with lowest mean MSE (averaged over 24 cells × 3 seeds)
3. Generates a unified shell sweep that runs:
   - Timer  bs=64, lr=3e-4, drop=<best>, ref_e=5  (re-uses existing run if best=10..50)
   - Moirai bs=32, lr=1e-4, drop=<best>, ref_e=5
   - MOMENT bs=64, lr=1e-4, drop=<best>, ref_e=5
4. Both Moirai and MOMENT use new refs (mixture_forecast / masked_recon_realtime).
5. Marks completion.

Constraints (per user task):
- Reference epochs = 5 fixed
- batch_size >= 32 (Timer:64, MOMENT:64, Moirai:32)
- full UTSD, 1 epoch
- "fair comparison": same drop_pct across all 3
"""
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path("/mnt/workspace/juyoung_ha/rho_pretrain/logs/auto_overnight")
OUT_SCRIPT = "/mnt/workspace/juyoung_ha/rho_pretrain/sweep_task1_unified.sh"


def mean_mse(label_rows):
    if not label_rows:
        return None
    return sum(r["test_mse"] for r in label_rows) / len(label_rows)


def best_drop_from_ablation():
    """Returns the drop_pct value with the lowest rho mean MSE.
    Looks across BOTH hosts (keti_1 and keti_2)."""
    candidates = {}   # drop -> rho_mse
    for d in [10, 15, 20, 25, 30, 35, 40, 45, 50]:
        for host in ('keti1', 'keti2'):
            run_dir = ROOT / f"{host}/timer__bs64_lr3e-4_e1_d{d}_re5"
            if not (run_dir / "DONE").exists():
                continue
            rho_mses = []
            for s in (42, 43, 44):
                p = run_dir / f"eval_seed{s}/zero_shot_results.json"
                if not p.exists():
                    continue
                data = json.loads(p.read_text())
                rho_rows = data.get("rho_cm", [])
                if rho_rows:
                    rho_mses.append(mean_mse(rho_rows))
            if len(rho_mses) >= 2:
                candidates[d] = sum(rho_mses) / len(rho_mses)
                break  # use first host where it's done

    if not candidates:
        print("[task1-B] No completed Timer drop ablation runs found yet.", flush=True)
        return None

    best = min(candidates, key=candidates.get)
    print(f"[task1-B] Drop ablation results (rho mean MSE):", flush=True)
    for d, m in sorted(candidates.items()):
        marker = " ← BEST" if d == best else ""
        print(f"  drop={d}: {m:.4f}{marker}", flush=True)
    return best


def write_unified_sweep(best_drop):
    moirai_baseline_src = ROOT / "keti1/moirai__bs32_lr1e-4_e1_d20/baseline"
    moment_baseline_src = ROOT / "keti2/moment__bs64_lr1e-4_e1_d10/baseline"
    timer_baseline_src  = ROOT / "keti2/timer__bs64_lr3e-4_e1_d20/baseline"
    timer_src_check = ROOT / f"keti2/timer__bs64_lr3e-4_e1_d{best_drop}_re5"

    template = f"""#!/usr/bin/env bash
# TASK1 Step B — unified drop_pct={best_drop} across 3 backbones (ref_e=5).
# Generated by task1_step_b_unified.py
set -uo pipefail

ROOT=/mnt/workspace/juyoung_ha/rho_pretrain
SWEEP=$ROOT/logs/auto_overnight
SUMMARY_K1=$SWEEP/keti1/summary.jsonl
SUMMARY_K2=$SWEEP/keti2/summary.jsonl
mkdir -p "$SWEEP/keti1" "$SWEEP/keti2"
touch "$SUMMARY_K1" "$SUMMARY_K2"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gracm
cd "$ROOT"

EVAL_SEEDS=(42 43 44)
EVAL_DATASETS=ETTh1,ETTh2,ETTm1,ETTm2,weather,exchange
EVAL_HORIZONS=96,192,336,720
DROP={best_drop}

# Backbone-specific best hparams — bs >= 32, ref_e = 5, full UTSD, 1 epoch
# Timer:  bs=64 lr=3e-4 (best from earlier sweeps)
# Moirai: bs=32 lr=1e-4 (best, packed-attn safe)
# MOMENT: bs=64 lr=1e-4 (best closest)

run_pair_unified () {{
  # backbone name batch lr script rho_mode eval_mode base_flag rho_flag eval_extra baseline_src host_summary
  local backbone=$1 name=$2 batch=$3 lr=$4 baseline_src=$5 host=$6
  local script rho_mode eval_mode base_flag rho_flag eval_json eval_extra
  case $backbone in
    timer)  script=scripts/pretrain_timer.py;  rho_mode=rho_cm;       eval_mode=eval_zero_shot_sweep; base_flag=--baseline-ckpt; rho_flag=--rho-cm-ckpt;       eval_json=zero_shot_results.json; eval_extra="";;
    moirai) script=scripts/pretrain_moirai.py; rho_mode=rho_cm;       eval_mode=eval_zero_shot_sweep; base_flag=--baseline-ckpt; rho_flag=--rho-cm-ckpt;       eval_json=zero_shot_results.json; eval_extra="";;
    moment) script=scripts/pretrain_moment.py; rho_mode=patch_rho_cm; eval_mode=eval_sweep;            base_flag=--baseline-ckpt; rho_flag=--patch-rho-cm-ckpt; eval_json=linear_probe_results.json; eval_extra="--probe-epochs 5";;
  esac

  local host_short="${{host//_/}}"   # keti_1 → keti1
  local out=$SWEEP/$host_short/${{backbone}}__${{name}}
  mkdir -p "$out"
  local marker=$out/DONE
  if [[ -f $marker ]]; then echo "[skip] $backbone/$name (DONE)"; return 0; fi

  echo "============================================"
  echo "[$(date '+%H:%M:%S')] $backbone/$name START (drop=$DROP, ref_e=5)"
  echo "============================================"

  if [[ ! -f $out/baseline/best.pt ]]; then
    if [[ -n "$baseline_src" && -f "$baseline_src/best.pt" ]]; then
      echo "[reuse] baseline ← $baseline_src"
      mkdir -p "$out/baseline"
      ln -sf "$baseline_src/best.pt" "$out/baseline/best.pt"
      [[ -f "$baseline_src/metrics.json" ]] && ln -sf "$baseline_src/metrics.json" "$out/baseline/metrics.json"
    else
      echo "[$(date '+%H:%M:%S')] baseline pretrain (no source)"
      mkdir -p "$out/baseline"
      python "$script" --mode baseline --epochs 1 --batch-size "$batch" --lr "$lr" \\
        --seed 42 --out-dir "$out/baseline" > "$out/baseline/pretrain.log" 2>&1
      [[ ! -f $out/baseline/best.pt ]] && {{ tail -20 "$out/baseline/pretrain.log"; return 1; }}
    fi
  fi

  if [[ ! -f $out/rho/best.pt ]]; then
    echo "[$(date '+%H:%M:%S')] rho pretrain"
    mkdir -p "$out/rho"
    python "$script" --mode "$rho_mode" --epochs 1 --batch-size "$batch" --lr "$lr" \\
      --seed 42 --drop-pct "$DROP" --ref-epochs 5 \\
      --out-dir "$out/rho" > "$out/rho/pretrain.log" 2>&1
    [[ ! -f $out/rho/best.pt ]] && {{ tail -30 "$out/rho/pretrain.log"; return 1; }}
  fi

  for seed in "${{EVAL_SEEDS[@]}}"; do
    local eval_out=$out/eval_seed${{seed}}
    [[ -f $eval_out/$eval_json ]] && {{ echo "[skip] eval seed=$seed exists"; continue; }}
    mkdir -p "$eval_out"
    echo "[$(date '+%H:%M:%S')] eval seed=$seed"
    python "$script" --mode "$eval_mode" --seed "$seed" \\
      --eval-datasets "$EVAL_DATASETS" --eval-horizons "$EVAL_HORIZONS" \\
      --out-dir "$eval_out" $eval_extra \\
      $base_flag "$out/baseline/best.pt" $rho_flag "$out/rho/best.pt" \\
      > "$eval_out/eval.log" 2>&1
    [[ ! -f $eval_out/$eval_json ]] && {{ tail -20 "$eval_out/eval.log"; return 1; }}
  done

  touch "$marker"
  local now=$(date '+%Y-%m-%dT%H:%M:%S')
  local summary_file
  [[ $host == keti_1 ]] && summary_file=$SUMMARY_K1 || summary_file=$SUMMARY_K2
  echo "{{\\"time\\":\\"$now\\",\\"host\\":\\"$host\\",\\"backbone\\":\\"$backbone\\",\\"name\\":\\"$name\\",\\"batch\\":$batch,\\"lr\\":$lr,\\"epochs\\":1,\\"drop_pct\\":$DROP,\\"ref_epochs\\":5,\\"task\\":\\"task1_unified\\",\\"status\\":\\"ok\\"}}" >> "$summary_file"
  echo "[$(date '+%H:%M:%S')] $backbone/$name DONE"
}}

# Run order: Timer (likely already done from ablation), then MOMENT/Moirai.
# Same machine should get backbones based on existing baselines.

# This script is run on EACH host separately — see launcher for host-specific calls.
HOST=$1   # keti_1 or keti_2

if [[ $HOST == keti_1 ]]; then
  # Moirai (keti_1) — uses Moirai mixture_forecast ref (script default)
  run_pair_unified moirai "bs32_lr1e-4_e1_d${{DROP}}_re5_unif" 32 1e-4 \\
    "$SWEEP/keti1/moirai__bs32_lr1e-4_e1_d20/baseline" "keti_1"
elif [[ $HOST == keti_2 ]]; then
  # Timer + MOMENT (keti_2)
  # Timer config might already exist from ablation:
  TIMER_FROM_ABLATION=$SWEEP/keti2/timer__bs64_lr3e-4_e1_d${{DROP}}_re5
  if [[ -f $TIMER_FROM_ABLATION/DONE ]]; then
    echo "[skip] timer config already done from ablation: $TIMER_FROM_ABLATION"
  else
    run_pair_unified timer "bs64_lr3e-4_e1_d${{DROP}}_re5_unif" 64 3e-4 \\
      "$SWEEP/keti2/timer__bs64_lr3e-4_e1_d20/baseline" "keti_2"
  fi
  # MOMENT — uses realtime masked-recon ref (script default)
  run_pair_unified moment "bs64_lr1e-4_e1_d${{DROP}}_re5_unif" 64 1e-4 \\
    "$SWEEP/keti2/moment__bs64_lr1e-4_e1_d10/baseline" "keti_2"
fi

echo "[$(date '+%H:%M:%S')] task1 unified ($HOST) ALL DONE"
"""
    with open(OUT_SCRIPT, "w", encoding='utf-8') as f:
        f.write(template)
    os.chmod(OUT_SCRIPT, 0o755)
    print(f"[task1-B] Wrote {OUT_SCRIPT}", flush=True)


def main():
    best = best_drop_from_ablation()
    if best is None:
        sys.exit(1)
    write_unified_sweep(best)


if __name__ == "__main__":
    main()
